import { rename, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

import { compareScores, DECK, evaluate, RANKS } from "../app/poker";

const trials = Math.max(10_000, Number(process.env.CAL_TRIALS) || 100_000);
const output = resolve(process.env.CAL_OUTPUT || "app/preflop-calibration.generated.ts");
const rankCodes = [...RANKS].reverse();

function seededRandom(seed: number) {
  let state = seed >>> 0;
  return () => {
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    return (state >>> 0) / 0x1_0000_0000;
  };
}

function representativeCards(high: string, low: string, suited: boolean) {
  if (high === low) return [`${high}s`, `${low}h`];
  return [`${high}s`, `${low}${suited ? "s" : "h"}`];
}

function simulate(hero: string[], seed: number) {
  const random = seededRandom(seed);
  const used = new Set(hero);
  const deck = DECK.filter((card) => !used.has(card));
  const totals = Array.from({ length: 8 }, () => ({ win: 0, tie: 0, lose: 0, equity: 0 }));
  const drawCount = 21;

  for (let sample = 0; sample < trials; sample++) {
    const swaps: number[] = [];
    for (let index = 0; index < drawCount; index++) {
      const target = index + Math.floor(random() * (deck.length - index));
      swaps.push(target);
      [deck[index], deck[target]] = [deck[target], deck[index]];
    }
    const board = deck.slice(0, 5);
    const heroScore = evaluate([...hero, ...board]);
    let tied = 0;
    let beaten = false;
    for (let opponent = 0; opponent < 8; opponent++) {
      const start = 5 + opponent * 2;
      const comparison = compareScores(heroScore, evaluate([deck[start], deck[start + 1], ...board]));
      if (comparison < 0) beaten = true;
      else if (comparison === 0) tied++;
      const outcome = totals[opponent];
      if (beaten) outcome.lose++;
      else if (tied) { outcome.tie++; outcome.equity += 1 / (tied + 1); }
      else { outcome.win++; outcome.equity++; }
    }
    for (let index = drawCount - 1; index >= 0; index--) {
      const target = swaps[index];
      [deck[index], deck[target]] = [deck[target], deck[index]];
    }
  }
  const rate = (value: number) => Number((value / trials * 100).toFixed(6));
  return totals.slice(1).map((outcome) => [rate(outcome.win), rate(outcome.tie), rate(outcome.equity)] as const);
}

const entries: Array<[string, ReadonlyArray<readonly [number, number, number]>]> = [];
let classIndex = 0;
for (let highIndex = 0; highIndex < rankCodes.length; highIndex++) {
  for (let lowIndex = highIndex; lowIndex < rankCodes.length; lowIndex++) {
    const high = rankCodes[highIndex];
    const low = rankCodes[lowIndex];
    const pair = high === low;
    for (const suited of pair ? [false] : [true, false]) {
      const highKey = high === "10" ? "T" : high;
      const lowKey = low === "10" ? "T" : low;
      const key = pair ? `${highKey}${lowKey}` : `${highKey}${lowKey}${suited ? "s" : "o"}`;
      entries.push([key, simulate(representativeCards(high, low, suited), 0x7f4a7c15 + classIndex * 0x9e3779b1)]);
      classIndex++;
    }
  }
}

const lines = entries.map(([key, rows]) => `  ${JSON.stringify(key)}:[${rows.map((values) => `[${values.join(",")}]`).join(",")}],`).join("\n");
const source = `// Generated by scripts/generate-preflop-calibration.ts with ${trials.toLocaleString("en-US")} deterministic trials per class.\n// Rows are opponents 2–8; values are [strict win, table tie, split-pot equity] percentages.\nexport const PREFLOP_MULTIWAY: Record<string, ReadonlyArray<readonly [number, number, number]>> = {\n${lines}\n};\n\nexport const PREFLOP_CALIBRATION_TRIALS = ${trials};\n`;
const temporaryOutput = join(dirname(output), `.${output.split(/[\\/]/).pop()}.${process.pid}.tmp`);
try {
  // Write the complete module elsewhere, then swap it into place. This keeps
  // dev-server file watchers from compiling the brief zero-byte state caused
  // by overwriting a large generated module in place.
  await writeFile(temporaryOutput, source, "utf8");
  await rename(temporaryOutput, output);
} finally {
  await rm(temporaryOutput, { force: true });
}
console.log(JSON.stringify({ classes: entries.length, trialsPerClass: trials, output }));
